// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/createSecureLink.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var allowedExpirations = /* @__PURE__ */ new Set([5, 30, 60, 1440, 10080]);
function getEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env.get(name) ?? runtime.process?.env?.[name];
}
function functionUrl(name) {
  const baseUrl = getEnv("SUPABASE_URL")?.replace(/\/+$/, "");
  if (!baseUrl) return { error: "Backend function URL is not configured." };
  return { url: `${baseUrl}/functions/v1/${name}` };
}
function functionHeaders() {
  const publishableKey = getEnv("SUPABASE_ANON_KEY") ?? getEnv("SUPABASE_PUBLISHABLE_KEY");
  return {
    "Content-Type": "application/json",
    ...publishableKey ? { apikey: publishableKey, Authorization: `Bearer ${publishableKey}` } : {}
  };
}
var createSecureLink_default = defineTool({
  name: "create_secure_link",
  title: "Create secure one-time link",
  description: "Encrypt a message and create a one-time access token for sharing it securely.",
  inputSchema: {
    content: z.string().describe("The secret message to encrypt."),
    expiresInMinutes: z.number().describe("Expiration in minutes. Use 5, 30, 60, 1440, or 10080.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ content, expiresInMinutes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Sign in is required to create secure links." }], isError: true };
    }
    const trimmedContent = content.trim();
    const minutes = Math.round(Number(expiresInMinutes));
    if (!trimmedContent) {
      return { content: [{ type: "text", text: "Content is required." }], isError: true };
    }
    if (!allowedExpirations.has(minutes)) {
      return {
        content: [{ type: "text", text: "Expiration must be one of: 5, 30, 60, 1440, or 10080 minutes." }],
        isError: true
      };
    }
    const endpoint = functionUrl("create-secure-link");
    if (endpoint.error) return { content: [{ type: "text", text: endpoint.error }], isError: true };
    const response = await fetch(endpoint.url, {
      method: "POST",
      headers: functionHeaders(),
      body: JSON.stringify({ content: trimmedContent, expiresInMinutes: minutes })
    });
    const payload = await response.json().catch(() => null);
    if (!response.ok || payload?.error || !payload?.accessToken) {
      return {
        content: [{ type: "text", text: payload?.error ?? "Failed to create a secure link." }],
        isError: true
      };
    }
    const viewPath = `#/view/${payload.accessToken}`;
    return {
      content: [
        {
          type: "text",
          text: `Secure link token created. Open this app at ${viewPath}. It expires at ${payload.expiresAt}.`
        }
      ],
      structuredContent: {
        accessToken: payload.accessToken,
        expiresAt: payload.expiresAt,
        viewPath
      }
    };
  }
});

// src/lib/mcp/tools/retrieveSecureLink.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function getEnv2(name) {
  const runtime = globalThis;
  return runtime.Deno?.env.get(name) ?? runtime.process?.env?.[name];
}
function functionUrl2(name) {
  const baseUrl = getEnv2("SUPABASE_URL")?.replace(/\/+$/, "");
  if (!baseUrl) return { error: "Backend function URL is not configured." };
  return { url: `${baseUrl}/functions/v1/${name}` };
}
function functionHeaders2() {
  const publishableKey = getEnv2("SUPABASE_ANON_KEY") ?? getEnv2("SUPABASE_PUBLISHABLE_KEY");
  return {
    "Content-Type": "application/json",
    ...publishableKey ? { apikey: publishableKey, Authorization: `Bearer ${publishableKey}` } : {}
  };
}
var retrieveSecureLink_default = defineTool2({
  name: "retrieve_secure_link",
  title: "Retrieve secure one-time link",
  description: "Consume a secure link access token and return the decrypted message exactly once.",
  inputSchema: {
    accessToken: z2.string().describe("The one-time access token from a SecureLink URL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ accessToken }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Sign in is required to retrieve secure links." }], isError: true };
    }
    const token = accessToken.trim();
    if (!token) {
      return { content: [{ type: "text", text: "Access token is required." }], isError: true };
    }
    const endpoint = functionUrl2("retrieve-secure-link");
    if (endpoint.error) return { content: [{ type: "text", text: endpoint.error }], isError: true };
    const response = await fetch(`${endpoint.url}?token=${encodeURIComponent(token)}`, {
      method: "GET",
      headers: functionHeaders2()
    });
    const payload = await response.json().catch(() => null);
    if (!response.ok || payload?.error || typeof payload?.content !== "string") {
      return {
        content: [{ type: "text", text: payload?.error ?? "Failed to retrieve the secure link." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: payload.content }],
      structuredContent: {
        content: payload.content,
        createdAt: payload.createdAt
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jcaiypgywqspwengpbsu";
var mcp_default = defineMcp({
  name: "securelink-mcp",
  title: "SecureLink MCP",
  version: "0.1.0",
  instructions: "Create encrypted one-time secure links and consume access tokens through SecureLink.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [createSecureLink_default, retrieveSecureLink_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
